### ISSUE TITLE
PGP key used for POM cannot be verified

### ISSUE THREAD

**Issue by sdavids** [xvik/gradle-animalsniffer-plugin#21]
https://docs.gradle.org/6.2/userguide/dependency_verification.html

build.gradle

```
plugins {
  id 'ru.vyarus.animalsniffer' version '1.5.0'
}

wrapper.configure {
  gradleVersion = '6.2.1'
}
```

Execute:

```
$ ./gradlew --write-verification-metadata pgp,sha256 help
...
A verification file was generated but some problems were discovered:
   - some artifacts aren't signed or the signature couldn't be retrieved.
   - some signature verification failed. Checksums were generated for those artifacts but you MUST check if there's an actual problem. Look for entries with the following comment: PGP verification failed
```

`gradle/verification-metadata.xml` will now have the following entry:

```
      <component group="ru.vyarus" name="gradle-animalsniffer-plugin" version="1.5.0">
...
         <artifact name="gradle-animalsniffer-plugin-1.5.0.pom">
            <ignored-keys>
               <ignored-key id="d35ad4aed58af7dba740648243f63fdd328b612f" reason="PGP verification failed"/>
            </ignored-keys>
            <sha256 value="40fc5b00119b1e5c2cdb6d6611876d065a40fcdcba87d37322dc86e520a67eed" origin="Generated by Gradle because PGP signature verification failed!"/>
         </artifact>
      </component>
```

**Comment by xvik** [comment]
Thank you for the info! 

I briefly read the documentation, but I did not see a way to know what exactly is wrong. I can only suspect [different checksums in different repos](https://docs.gradle.org/6.2/userguide/dependency_verification.html#sec:trusting-several-checksums). If this is the case, then it's true, poms are different in gradle plugin portal and maven central/jcenter: [plugin portal pom](https://plugins.gradle.org/m2/ru/vyarus/gradle-animalsniffer-plugin/1.5.0/gradle-animalsniffer-plugin-1.5.0.pom), [maven central pom](https://repo1.maven.org/maven2/ru/vyarus/gradle-animalsniffer-plugin/1.5.0/gradle-animalsniffer-plugin-1.5.0.pom).

I can't do anything about it, simply because gradle plugin-publish plugin did not use my generated pom for plugin publication.

Please tell me if I'm wrong and the reason is different. I would appreciate any advice on how to deal with this problem.

**Comment by sdavids** [comment]
Was a cache problem unfortunately 😕

**Comment by xvik** [comment]
Thank you for the info! I'm happy to know its not an issue :)
