### ISSUE TITLE
Failed to check signatures error after upgrading to Gradle 5.6.4

### ISSUE THREAD

**Issue by jakubvimn** [xvik/gradle-animalsniffer-plugin#22]
After updating gradle in the project
https://github.com/hierynomus/license-gradle-plugin/pull/184/files
the task `:animalsnifferMain` fails with error
`Failed to check signatures`
The stacktrace contais the following exception:

`Caused by: java.io.IOException:  failed to process jar /Users/krolewsj/.gradle/caches/5.6.4/generated-gradle-jars/gradle-api-5.6.4.jar : Bad class file /Users/krolewsj/.gradle/caches/5.6.4/generated-gradle-jars/gradle-api-5.6.4.jar:org/gradle/internal/impldep/META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils.class
`
Any idea what to do?

**Comment by xvik** [comment]
'Bad class file': animalsniffer's shaded asm does not support java 9 classes.
It fails reading exactly java 9 classes (multi-release jar): `META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils.class`

By default, plugin depends on 1.16 because 1.17 release (with java 9 support) breaks java 8 support, but recently 1.18 was released fixing this problem.

So the workaround is:

```groovy
animalsniffer {
    toolVersion = '1.18'
}
```

I will look to release a new plugin version with updated default (if everything is ok with the new animalsniffer release ofc).

**Comment by xvik** [comment]
released: https://github.com/xvik/gradle-animalsniffer-plugin/releases/tag/1.5.1
