### ISSUE TITLE
Leverage @CompileClasspath from Gradle 3.4

### ISSUE THREAD

**Issue by szpak** [xvik/gradle-animalsniffer-plugin#4]
Gradle 3.4 (released in February 2017) has introduced [`@CompileClasspath`](https://docs.gradle.org/3.4/javadoc/org/gradle/api/tasks/CompileClasspath.html) annotation for tasks depending on classpath elements. As it aware of a class signature it may be somehow more resilient to changes than plain `@InputFiles`.

**Comment by xvik** [comment]
I tried to experiment with this and I didn't find situations where it could be useful. It would be great if it could skip task for some source changes (e.g. adding a comment), but it can't prevent that.
Probably, it could prevent task execution in case of minor classpath changes, but I doubt you will notice this (usually classpath changes quite rare).
Even gradle itself use this annotation only for java compile task.

Do you have a real life problem you're trying to solve with this? 
Or do you know cases where it would lead to benefits?. 
I need something real because right now I don't see any good reason for this change.

**Comment by szpak** [comment]
I've been playing with your plugin in [Mockito](https://github.com/mockito/mockito/pull/1021) recently and it was a little bit disappointing that a change in one file seems to trigger checking all the classes in the project (around 4 seconds). Currently I do it conditionally (only if compatibility mode is enabled to mitigate an overhead), but it would be great to have just that one file being re-checked. I haven't played with `CompileClasspath` on my own, but I though it is a little bit smarted (e.g. to detect signatures in which classes have been effectively modified). I don't know if something like [IncrementalTaskInputs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.incremental.IncrementalTaskInputs.html) could be used for classes.

**Comment by xvik** [comment]
Mockito build uses gradle 2.14.1, so it will not benefit from `@CompileClasspath` in any case. But, based on what I read about it already, it can't help in our case in any way.

Supporting incremental is an interesting idea. Incremental support was introduced in 2.1 so mockito build could (potentially) benefit from it. I will read more about it and try to experiment.

**Comment by szpak** [comment]
2.14.1 is used to have Java 6 support (Gradle 3 dropped support for it), but we are migrating 2.x branch to build with Java 7 for Java 6 (which is a reason why animalsniffer is needed :) ). Therefore, Gradle will be upgraded to newer version once a transition is done. Please comment have if you have any progress to let me test it :).

**Comment by szpak** [comment]
Regarding `@Classpath` you may want to give 3.5-rc a [try](https://docs.gradle.org/3.5-rc-3/release-notes.html#more-work-avoidance-when-using-@classpath-task-properties)

```
In previous versions, for tasks like Javadoc, Checkstyle and Test, Gradle would consider the task out-of-date if the content of the classpath changed in any way (order of classes in a jar, timestamps of class files, etc).
```

**Comment by xvik** [comment]
Committed incremental build support. Could you test it from source?

Incremental mode is disabled by default.
```groovy
animalsniffer {
    incremental = true
}
````

**Comment by szpak** [comment]
Yes, I will.

**Comment by szpak** [comment]
With Gradle 2.14 it fails with:

```
:classes UP-TO-DATE
:animalsnifferMain

[Undefined reference] org.mockito.(ArgumentCaptor.java:65)
  >> org.mockito.internal.matchers.CapturingMatcher

[Undefined reference] org.mockito.(ArgumentCaptor.java:65)
  >> void org.mockito.internal.matchers.CapturingMatcher.<init>()

[Undefined reference] org.mockito.(ArgumentCaptor.java:83)
  >> Object org.mockito.Mockito.argThat(org.mockito.ArgumentMatcher)

[Undefined reference] org.mockito.(ArgumentCaptor.java:84)
  >> Object org.mockito.internal.util.Primitives.defaultValue(Class)

[Undefined reference] org.mockito.(ArgumentCaptor.java:97)
  >> Object org.mockito.internal.matchers.CapturingMatcher.getLastValue()

[Undefined reference] org.mockito.(ArgumentCaptor.java:135)
  >> java.util.List org.mockito.internal.matchers.CapturingMatcher.getAllValues()

:animalsnifferMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':animalsnifferMain'.
> 6 AnimalSniffer violations were found in 1 files. See the report at: file:////home/fooCode/mockito/build/reports/animalsniffer/main.text
```

After a single change in `ArgumentCaptor.java` file.

You can reproduce that issue by changing a line 133 in the `ArgumentCaptor.java` in my [branch](https://github.com/szpak/mockito/tree/animalsnifferIncrementalIssue) and running `gw animalsnifferMain animalsnifferTest`.

**Comment by szpak** [comment]
The same with 3.5-rc-3.

**Comment by xvik** [comment]
I didn't count that animalsniffer always treat missed class as the error. So when it runs only on changed classes, it is not aware of all other classes in the project (not changed).

I workaround this by manually adding all not changed classes to ignored classes. This obviously adds additional work and reduce the benefit of an incremental build.

I played with your branch and, honestly, I don't see a good reason for incremental builds at all. Animalsniffer task execution takes just ~1.5s. And I dont see much benefit from incremental build.

Here is not incremental run: `gradlew animalsnifferMain --rerun-tasks --profile`:

Task | |	Duration | 	Result
------|-|--------------|--------------
: | |	7.192s |	(total)
 |:jar |	3.672s |	
. |:compileJava |	2.299s |	
. |**:animalsnifferMain** |	**1.189s** |	
. |:copyMockMethodDispatcher |	0.031s |	
. |:processResources |	0.001s |	UP-TO-DATE
. |:classes |	0s |	Did No Work
:android | |	1.476s |	(total)
. |**:android:animalsnifferMain** |	**1.169s** |	
. |:android:compileJava |	0.285s |	
. |:android:processResources |	0.022s |	
. |:android:classes |	0s |	Did No Work
:testng | |	1.452s |	(total)
. |**:testng:animalsnifferMain** |	**0.982s** |	
. |:testng:compileJava |	0.470s |	
. |:testng:classes |	0s |	Did No Work
. |:testng:processResources |	0s |	UP-TO-DATE
:inline | |	0.598s |	(total)
. |**:inline:animalsnifferMain** |	**0.577s** |	
. |:inline:processResources |	0.020s |	
. |:inline:compileJava |	0.001s |	UP-TO-DATE
. |:inline:classes |	0s |	Did No Work
:extTest | |	0s |	(total)
. |**:extTest:animalsnifferMain** |	**0s** |	UP-TO-DATE
. |:extTest:classes |	0s |	UP-TO-DATE
. |:extTest:compileJava |	0s |	UP-TO-DATE
. |:extTest:processResources |	0s |	UP-TO-DATE

And the incremental run with usy one file changed: `gradlew animalsnifferMain --profile`:

Task | |	Duration |	Result
-----|-|--------------|-------------
: | |	5.783s|	(total)
. | :jar| 	2.981s|	
. | :compileJava |	1.948s |	
. | **:animalsnifferMain** |	**0.852s** |	
. | :copyMockMethodDispatcher |	0.002s |	UP-TO-DATE
. | :classes |	0s |	Did No Work
. | :processResources |	0s |	UP-TO-DATE
:testng | |	0.688s |	(total)
. | **:testng:animalsnifferMain** |	**0.541s** |	
. | :testng:compileJava |	0.146s |	
. | :testng:classes |	0.001s |	Did No Work
. | :testng:processResources |	0s |	UP-TO-DATE
:android | |	0.684s |	(total)
. | **:android:animalsnifferMain** |	**0.508s** |	
. | :android:compileJava |	0.170s |	
. | :android:processResources |	0.006s |	UP-TO-DATE
. | :android:classes |	0s |	Did No Work
:inline | |	0.534s |	(total)
. | **:inline:animalsnifferMain** |	**0.530s** |	
. | :inline:processResources |	0.003s |	UP-TO-DATE
. | :inline:compileJava |	0.001s |	UP-TO-DATE
. | :inline:classes |	0s |	UP-TO-DATE
:extTest | |	0.001s |	(total)
. | :extTest:compileJava |	0.001s |	UP-TO-DATE
. | **:extTest:animalsnifferMain** |	**0s** |	UP-TO-DATE
. | :extTest:classes |	0s |	UP-TO-DATE
. | :extTest:processResources |	0s|	UP-TO-DATE

Please tell me after your experiments if you can see any good reason for the incremental build.

The current implementation is still incomplete because there must be extra checks for classpath changes to catch situation when signature file changes, but no classes checked because no sources changed. This will also add additional overhead (not much ofc) and complicate plugin.

For now, I don't see enough reasons to keep this feature.. the benefit is too small.

**Comment by szpak** [comment]
Thanks for your analysis. I will play with it, however, one thing wonders me right now. Do the `animalSniffer` tasks from other modules need to be executed if a file in the other module is modified? I don't know why animalsniffer works under the hood, but maybe it is related to takes other "own" classes into the account to get know if it is a know construction.

Btw, yesterday I profiled animalsniffer execution in my other project written in Groovy - [gradle-nexus-staging-plugin/](https://github.com/Codearte/gradle-nexus-staging-plugin/). It turned out that for quite small Groovy project the execution time is quite long (probably due to extra Groovy method added under the hood):

```
:animalsnifferFuncTest 	10.316s 	
:animalsnifferTest 	9.602s 	
:animalsnifferMain 	9.430s 	
```

Nevertheless, maybe you are right that running animalsniffer tasks only on demand is enough not to mention to its simplicity in implementation.

**Comment by xvik** [comment]
It was a great hint to check groovy project! Thank you!
It appears that we were fighting the wrong beast :) 

Most of the time task spent reading all classes from classpath jars. In case of groovy gradle plugin, this means reading all classes from groovy-all and gradle-api...

It should be possible to cache this stage by building a new signature for the entire classpath. So there will be another cacheable task which will prepare project specific signature and speed up all future animalsniffer launches.

This should also fix plugin behavior for multiple signatures: now it runs animalsniffer for each configured signature consequently, which is wrong. Also, it would be natural to make signature building task general for building project-specific signatures (like in maven plugin).

Implementing all this may take some time (hopefully few days), but it should solve all problems.

**Comment by szpak** [comment]
Sounds great! Good luck with the implementation :).

**Comment by xvik** [comment]
It took much longer than I expect, but now it's almost ready. There may be some minor changes, but I think the final release should be soon. 

I will briefly describe it in case if you have time to play with it or will see an issue just out of the description (sorry, long read).

Incremental logic, that I showed you before was completely removed.
Now there is an additional task for each animalsniffer check task, which builds source set specific signature from configured signatures and source set's compile classpath. For example, animalsnifferResourcesMain build signatures for animalsnifferMain. This makes the first run a bit slower than before, but subsequent runs faster (especially for projects with large classpath). Of course, clean will force signature re-build again, but in other cases only check task will run.

In multi-module projects (like mockito), modules depend on each other and so module classpath could change quite often. To avoid re-generating check signatures too often, project module jars are not included in generated signature (and used directly on check task). This way, specific signatures are cached for a long time (usually, until next clean).

There is an ability to switch off resource tasks and do everything as before (legacy mode):
```
animalsniffer {
    useResourcesTask = false
}
```
So it's very easy to compare old/new approaches.

And there is a small optimization: most of the time, we dont use all apis from java signature and all api from jars, so we could cut off not used apis and reduce resulted signature size - this will improve check task speed (as it would load smaller signature).

For example, jdk signature contains 18312 classses with 4636 in sun.* package (which is never used by sane people). com.sun.* contains 7115 classes (could be used, but still rare). Gradle-api.jar contains 16239 classes of repackaged 3rd parties.

By default, I exclude sun.* and org.gradle.internal.impldep.* (gradle 3rd parties) from generated signatures, so, with resources tasks, check task will already use smaller signature.
Other exclusions may be configured:

```
animalsniffer {
      resourcesExclude 'com.sun.*', 'javax.swing.*'
}
```
(this will not remove default exclusions)

To be able to shrink signature further, there is a special task to analyze signature. For example, to see generated signature for a check task:
```
task printSignature(type: ru.vyarus.gradle.plugin.animalsniffer.info.SignatureInfoTask) {
                signature = animalsnifferResourcesMain.outputs.files
                depth = 2
                sortBySize = true
} 
```
For java signature (declared in dependencies): `signature = configurations.signature` (example below for depth 1)

```
Signature java16-sun-1.0.signature (1.7 Mb) contains 18312 classes
	com                 7115
	java                 2441
	javax                3327
	org                  790
	sun                  4636
	sunw                 3
```

And, of course, there is now an easy way to generate signatures for the project, but I will not describe it as not relevant.

**Comment by szpak** [comment]
Unfortunately I will not be able to play with it before weekend. However, it looks very promising :).

**Comment by szpak** [comment]
I gave it a try with Mockito. The overall animalsniffer execution time is slightly lower (in comparison to the previous version - probably thanks to signatures exclusion) and the consecutive calls (with a small change) is even lower (`Resources` tasks are cached - only `ResourcesTest` from the module with a changed class is rebuilt).
The biggest difference, however, is visible in my Groovy project. The execution time of `animalsnifferMain` after just small change dropped from ~9 seconds to less than 1. Nice! Thanks for your work.

**Comment by xvik** [comment]
The new version is finally [released](https://github.com/xvik/gradle-animalsniffer-plugin/releases/tag/1.4.0), but with some changes (relative to my last comment).

By default, the plugin will work as before, because it is more oriented now on using multiple signatures ([jdk and android](https://github.com/xvik/gradle-animalsniffer-plugin#signatures)). Performance optimization is now called "cache". To enable it you need:

```groovy
animalsniffer {
    cache.enabled = true
}
```

As before, cached signature [could be reduced](https://github.com/xvik/gradle-animalsniffer-plugin/wiki/Check-task-performance).

There is a new highlighted use case to [use animalsniffer signatures to check 3rd party libraries](https://github.com/xvik/gradle-animalsniffer-plugin/wiki/Library-signatures). I doubt it would be popular use, but in some cases, it could be an option.

It's been a while since my last comment and not sure you're still tracking this so I will close the issue. 
Thank you for this issue and all feedback! Without it, the plugin would never reach its current state.
