### ISSUE TITLE
Plugin doesn't work if used in conjunction with retrolambda

### ISSUE THREAD

**Issue by devLotto** [xvik/gradle-animalsniffer-plugin#7]
gradle-animalsniffer-plugin version 1.4.3
gradle-retrolambda version 3.7.0 - https://github.com/evant/gradle-retrolambda
Gradle wrapper version 4.8

Using this plugin without retrolambda, the build spits out the correct output:

```java
Execution failed for task ':animalsnifferMain'.
> 3 AnimalSniffer violations were found in 1 files.
```

The second I add the retrolambda plugin to the build, animal sniffer starts not outputting anything, and the build goes through without erroring, which is wrong.

I've observed that this only seems to happen if there are classes with lambdas (that retrolambda has processed) in the classpath. If there are no lambdas in my code, animalsniffer correctly catches use of disallowed API even when retrolambda is enabled. 

I have no clue if animalsniffer or retrolambda is at fault here. Maybe this has something to do with how retrolambda handles classes?

Files to reproduce:

build.gradle:

```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'ru.vyarus:gradle-animalsniffer-plugin:1.4.3'
    }
}

plugins {
    id 'java'
    id 'ru.vyarus.animalsniffer' version '1.4.3'
    id 'me.tatarka.retrolambda' version '3.7.0'
}

repositories {
    mavenCentral()
}

dependencies {
    // Restrict API usage to Android API level 21
    signature 'net.sf.androidscents.signature:android-api-level-21:5.0.1_r2@signature'
}
```

Test method:

```java
public static void main(String[] args) {
        List<String> b = new ArrayList<>();
        b.stream().forEach(System.out::println);
}
```

**Comment by xvik** [comment]
Thank you, I will look closer as soon as I can. Gradle 4.8 break my other plugins and I'm trying to fix them now.

At first look, the problem seems to be that retrolambda plugin [changes output directory for compileJava tasks](https://github.com/evant/gradle-retrolambda/blob/master/gradle-retrolambda/src/main/groovy/me/tatarka/RetrolambdaPluginJava.groovy#L47). Animalsniffer plugin [depends on java compile](https://github.com/xvik/gradle-animalsniffer-plugin/blob/master/src/main/groovy/ru/vyarus/gradle/plugin/animalsniffer/AnimalSnifferPlugin.groovy#L154) so most likely: animalsniffer calls compileJava with changed destination - no visible classes - no violations. 

A possible fix could be something like `animalsnifferMain.dependsOn compileRetrolambdaMain`. If you have time, you can try to apply this workaround and see if it helps.

**Comment by xvik** [comment]
There were 2 issues: 
* Plugin eats errors (so report was empty because plugin actually failed)
* All classes for check are passed as path into ant task and ant was removing every second (consequent) $  and so animalsniffer did not see correct files: instead of `Somehting$$Lambda$1.class` it was trying to access `Something$Lambda$1.class`.. and fail.

Now it will work.
